# Define the goal
geometry_msgs/Pose[] box_poses
---
# Define the result
geometry_msgs/Pose[] box_order          # picking order based on position in the box vector
---
# Define a feedback message
# Nothing